### ISSUE TITLE
Model weights?

### ISSUE THREAD

**Issue by SebasGarcia08** [DoctorKey/C-3PO#2]
Hi, congratulations on the excellent work!  Where can be accessed the weights of the models presented in the results table?

**Comment by DoctorKey** [comment]
Thanks. I will re-train some models and release them recently.

**Comment by SebasGarcia08** [comment]
Excellent! Thank you. I'll stay tuned.

**Comment by DoctorKey** [comment]
I have released several models. Please check README for more details.
