### ISSUE TITLE
Device parameter

### ISSUE THREAD

**Issue by timmermansjoy** [DoctorKey/C-3PO#6]
in the main train.py script you can pass the device param. but there is a lot of stuff cuda Is used for and can't use the CPU to do anything? is this meant to do stuff like `cuda:4` or so?

**Comment by timmermansjoy** [comment]
Okay, I'm having trouble getting it up and running due to the fact all those datasets seem to be broken / not available for download

**Comment by DoctorKey** [comment]
Please check README. I have updated the download link. You can download `VL-CMU-CD-binary255` at [here](https://huggingface.co/datasets/Flourish/VL-CMU-CD/blob/main/VL-CMU-CD-binary255.zip).
