### ISSUE TITLE
ModuleNotFoundError: No module named 'correlation_cuda'

### ISSUE THREAD

**Issue by timmermansjoy** [DoctorKey/C-3PO#7]
When trying to run the train script I get the `ModuleNotFoundError: No module named 'correlation_cuda'` error. I have tried this on my local machine and on a server from [lambdalabs](https://lambdalabs.com) but both don't seem to work and keep getting stuck on the correlation_cuda issue

**Comment by DoctorKey** [comment]
You should install the `correlation` module.

Overall, if you want to use CSCDNet in our project, please follow their [instructions](https://github.com/kensakurada/sscdnet) to install the `correlation` module.

If you do not want to use other models or install unnecessary packages, please checkout the `mini` branch, which only contains codes for our C-3PO model.

**Comment by KelvinCPChiu** [comment]
Go to the foloder of the correlation under src and run
`pip install -e .`

**Comment by shang-an6** [comment]
> 进入src下的相关文件夹并运行 `pip ins你好请问我运行之后为什么报这个错呢ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by shang-an6** [comment]
> When trying to run the train script I get the `ModuleNotFoundError: No module named 'correlation_cuda'` error. I have tried this on my local machine and on a server from [lambdalabs](https://lambdalabs.com) but both don't seem to work and keep getting stuck on the correlation_cuda issue


What was the final solution?
